In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import os
import pickle

In [2]:
with open("data.txt",'r',encoding='utf-8') as f :
    text_data  = f.read()

In [3]:
text_data

"my name is sudhanshu kumar , i work with euron , Helping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.\nHelping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.Sudhanshu Kumar's life is a story of triumph over adversity, driven by the belief in the transformative power of education. Born in Jamshedpur, Jharkhand, India, to a family of very modest means, Sudhanshu's early years were marked by financial hardship. His surroundings offered little opportunity, and resources were limited, yet he understood from a young age that education could be his ticket out of poverty.\n\nWhile many would have been daunted by the lack of support and opportunity, Sudhanshu was relentless in his pursuit of knowledge. He knew that education had the power to change lives, and he was determined to leverage it to create a better future for himself and his family. Despite the numerous challenges along the way, Sudhanshu excelled academically, eventually earning a degree in Computer Science and Engineering (CSE).\nAfter completing his education, Sudhanshu began his professional journey in the tech industry, working with prestigious companies like Wipro, Deloitte, Verizon Labs, and Ernst & Young. During this time, he gained expertise in various technologies and frameworks, including SAP WebDynpro, Fiori UI5 HANA, Java, Big Data, Data Analytics, and more. He became a well-rounded technologist, well-respected in his field.\n\nDespite his growing success, Sudhanshu never forgot his roots. He knew that there were many others who, like him, came from humble backgrounds and were looking for an opportunity to change their lives through education. It was during this time that Sudhanshu realized a harsh truth: quality education was often inaccessible to those who needed it the most. The high cost of education barred millions of people from pursuing their dreams, especially in tech fields that required specialized skills.\nFueled by his passion for making education accessible, Sudhanshu decided to take action. In 2019, he founded iNeuron Intelligence Private Limited, an edtech platform that would make tech upskilling affordable and accessible for everyone. His mission was clear: to provide high-quality courses at a price so low that even those from the most disadvantaged backgrounds could afford to learn.\n\niNeuron was designed to be more than just an online learning platform. It offered a comprehensive bundle of resources, including courses, books, hands-on projects, and live classes, making sure that learners could gain real-world, applicable skills. Most importantly, iNeuron was priced to ensure no student would be left behind due to financial constraints.\n\nThe company quickly gained traction, thanks to Sudhanshu's focus on affordability and quality. In 2021, iNeuron raised $3 million in funding from S. Chand, a leading education publisher. This allowed iNeuron to expand its offerings and reach a larger audience.\nBuilding on the success of iNeuron, Sudhanshu is now leading Euron, a unified platform for tech upskilling. Euron is designed for enterprises, schools, colleges, government organizations, and individuals looking to improve their tech skills. The platform provides a comprehensive bundle of resources, including courses, books, live classes, and projects. Euron's unique offering is its ability to provide licenses at scale—organizations can subscribe to provide their teams with unlimited access to learning materials for just 1600 INR per year per license.\n\nFor individuals, Euron Plus offers a similar plan, priced at 2900 INR per year, giving learners access to all of Euron's content, along with 24/7 support through Euron Assist. The idea is simple: anyone, anywhere, should have the opportunity to upskill without financial barriers.\n\nThe Euron Motto: Education for All, Without Limits\n\nAt the heart of Euron's philosophy is a single, powerful idea: Education for All, Without Limits. Sudhanshu believes that every person deserves the chance to learn, grow, and succeed, regardless of their financial situation or background. This belief is what drives Euron's mission to make tech education not just affordable but also accessible to anyone, anywhere in the world."

In [4]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=5000,oov_token='<OOV>')
tokenizer.fit_on_texts([text_data])

In [5]:
tokenizer

In [10]:
sequence = tokenizer.texts_to_sequences([text_data])[0]

In [14]:
sequence

[158,
 159,
 16,
 9,
 160,
 161,
 162,
 20,
 21,
 69,
 49,
 5,
 22,
 28,
 36,
 70,
 2,
 23,
 10,
 71,
 29,
 4,
 72,
 73,
 12,
 8,
 74,
 24,
 30,
 3,
 50,
 11,
 75,
 76,
 30,
 77,
 78,
 51,
 22,
 14,
 79,
 80,
 81,
 82,
 20,
 3,
 31,
 37,
 83,
 2,
 28,
 6,
 84,
 85,
 86,
 87,
 38,
 5,
 88,
 22,
 39,
 9,
 52,
 53,
 14,
 54,
 40,
 37,
 89,
 11,
 90,
 4,
 91,
 25,
 2,
 92,
 93,
 18,
 94,
 6,
 95,
 11,
 12,
 96,
 26,
 97,
 6,
 4,
 98,
 99,
 100,
 101,
 55,
 27,
 41,
 12,
 4,
 102,
 103,
 9,
 104,
 105,
 32,
 8,
 24,
 56,
 57,
 3,
 41,
 11,
 106,
 2,
 107,
 108,
 5,
 3,
 33,
 23,
 7,
 34,
 17,
 35,
 6,
 3,
 42,
 69,
 49,
 5,
 22,
 28,
 36,
 70,
 2,
 23,
 10,
 71,
 29,
 4,
 72,
 73,
 12,
 8,
 74,
 24,
 30,
 3,
 50,
 11,
 75,
 76,
 30,
 77,
 78,
 51,
 22,
 14,
 79,
 80,
 81,
 82,
 20,
 3,
 31,
 37,
 83,
 2,
 28,
 6,
 84,
 85,
 86,
 87,
 38,
 5,
 88,
 22,
 39,
 9,
 52,
 53,
 14,
 54,
 40,
 37,
 89,
 11,
 90,
 4,
 91,
 25,
 2,
 92,
 93,
 18,
 94,
 6,
 95,
 11,
 12,
 96,
 26,
 97,
 6,
 4,
 98,
 99,
 100,
 101,
 55,
 27,
 41,
 12,
 4,
 102,
 103,
 9,
 104,
 105,
 32,
 8,
 24,
 56,
 57,
 3,
 41,
 11,
 106,
 2,
 107,
 108,
 5,
 3,
 33,
 23,
 7,
 34,
 17,
 35,
 6,
 3,
 42,
 9,
 163,
 164,
 16,
 4,
 165,
 5,
 166,
 30,
 167,
 168,
 26,
 3,
 109,
 6,
 3,
 169,
 110,
 5,
 10,
 170,
 6,
 171,
 172,
 173,
 2,
 4,
 111,
 5,
 174,
 175,
 176,
 36,
 177,
 50,
 43,
 178,
 26,
 44,
 179,
 8,
 180,
 112,
 181,
 25,
 7,
 58,
 43,
 113,
 182,
 19,
 183,
 14,
 4,
 114,
 184,
 15,
 10,
 59,
 60,
 8,
 185,
 186,
 5,
 187,
 55,
 38,
 61,
 115,
 188,
 189,
 26,
 3,
 190,
 5,
 116,
 7,
 25,
 9,
 12,
 191,
 6,
 8,
 192,
 5,
 193,
 19,
 117,
 15,
 10,
 194,
 3,
 110,
 2,
 118,
 119,
 7,
 19,
 12,
 195,
 2,
 196,
 45,
 2,
 197,
 4,
 198,
 199,
 13,
 52,
 7,
 8,
 111,
 120,
 3,
 200,
 201,
 121,
 3,
 202,
 9,
 203,
 204,
 205,
 206,
 4,
 207,
 6,
 208,
 209,
 7,
 210,
 211,
 57,
 212,
 8,
 10,
 9,
 213,
 8,
 214,
 215,
 6,
 3,
 17,
 216,
 217,
 20,
 218,
 219,
 39,
 220,
 221,
 222,
 223,
 7,
 224,
 114,
 122,
 27,
 123,
 19,
 124,
 225,
 6,
 226,
 227,
 7,
 228,
 62,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 125,
 125,
 236,
 7,
 126,
 19,
 237,
 4,
 127,
 238,
 239,
 127,
 240,
 6,
 8,
 241,
 120,
 8,
 242,
 128,
 9,
 243,
 244,
 8,
 245,
 19,
 117,
 15,
 246,
 43,
 38,
 247,
 129,
 39,
 248,
 53,
 14,
 249,
 40,
 7,
 43,
 130,
 13,
 63,
 25,
 2,
 118,
 18,
 119,
 131,
 10,
 45,
 12,
 122,
 27,
 123,
 15,
 9,
 250,
 4,
 251,
 252,
 64,
 10,
 12,
 253,
 254,
 2,
 132,
 129,
 255,
 45,
 3,
 33,
 3,
 133,
 256,
 5,
 10,
 257,
 49,
 5,
 258,
 14,
 259,
 18,
 260,
 261,
 6,
 17,
 262,
 15,
 263,
 264,
 31,
 265,
 26,
 8,
 266,
 13,
 134,
 10,
 34,
 9,
 267,
 2,
 268,
 269,
 6,
 270,
 19,
 271,
 11,
 272,
 273,
 113,
 63,
 274,
 46,
 15,
 61,
 135,
 17,
 136,
 23,
 7,
 34,
 13,
 275,
 8,
 24,
 12,
 276,
 2,
 65,
 133,
 64,
 35,
 47,
 4,
 277,
 278,
 279,
 15,
 56,
 132,
 14,
 3,
 33,
 54,
 40,
 59,
 280,
 2,
 137,
 11,
 12,
 138,
 2,
 60,
 126,
 281,
 29,
 63,
 282,
 139,
 46,
 45,
 112,
 4,
 140,
 141,
 5,
 58,
 62,
 35,
 142,
 283,
 32,
 143,
 7,
 144,
 145,
 134,
 284,
 15,
 146,
 59,
 285,
 286,
 42,
 287,
 31,
 33,
 288,
 11,
 12,
 147,
 2,
 289,
 290,
 291,
 61,
 60,
 292,
 293,
 294,
 2,
 44,
 295,
 3,
 296,
 297,
 124,
 298,
 299,
 2,
 36,
 300,
 32,
 301,
 7,
 64,
 6,
 302,
 11,
 303,
 304,
 51,
 6,
 305,
 14,
 306,
 307,
 4,
 148,
 10,
 308,
 27,
 309,
 11,
 2,
 310,
 149,
 311,
 7,
 312,
 4,
 313,
 314,
 315,
 32,
 3,
 128,
 5,
 11,
 9,
 16,
 316,
 148,
 21,
 4,
 317,
 46,
 13,
 17,
 136,
 21,
 16,
 138,
 13,
 318,
 319,
 320,
 321,
 322,
 7,
 150,
 130,
 2,
 323,
 18,
 17,
 31,
 3,
 46,
 324,
 4,
 140,
 141,
 5,
 58,
 62,
 35,
 142,
 144,
 145,
 7,
 143,
 48,
 325,
 326,
 16,
 149,
 327,
 2,
 65,
 328,
 47,
 329,
 330,
 331,
 2,
 65,
 18,
 332,
 20,
 333,
 151,
 2,
 139,
 334,
 13,
 29,
 335,
 152,
 66,
 153,
 66,
 336,
 13,
 150,
 21,
 337,
 338,
 4,
 339,
 340,
 147,
 47,
 341,
 152,
 66,
 153,
 342,
 146,
 151,
 2,
 67,
 5,
 48,
 343,
 121,
 20,
 344,
 345,
 116,
 131,
 21,
 346,
 3,
 154,
 16,
 347,
 155,
 156,
 348,
 115,
 3,
 25,
 2,
 349,
 68,
 44,
 350,
 3,
 21,
 351,
 10,
 13,
 67,
 68,
 157,
 47,
 3,
 352,
 5,
 48,
 353,
 16,
 4,
 354,
 355,
 154,
 10,
 13,
 67,
 68,
 157,
 9,
 356,
 15,
 357,
 358,
 359,
 3,
 360,
 2,
 137,
 361,
 7,
 28,
 362,
 5,
 18,
 44,
 363,
 364,
 365,
 27,
 109,
 16,
 366,
 367,
 48,
 24,
 2,
 135,
 17,
 10,
 368,
 29,
 23,
 369,
 370,
 34,
 2,
 155,
 156,
 6,
 3,
 42]

In [12]:
len(sequence)

860

In [13]:
with open("tokenizer.pkl",'wb')  as f :
    pickle.dump(tokenizer,f)

In [26]:
max_seq_length = 100
def create_dataset(seq,window_size = max_seq_length):
    input ,labels = [],[]
    for i in range(len(seq) -window_size):
        input.append(seq[i:i+window_size])
        labels.append(seq[i+1:i+window_size+1])
    return np.array(input) , np.array(labels)

In [27]:
x_data , y_data = create_dataset(sequence)

In [28]:
len(x_data)

760

In [29]:
x_data[0]

array([158, 159,  16,   9, 160, 161, 162,  20,  21,  69,  49,   5,  22,
        28,  36,  70,   2,  23,  10,  71,  29,   4,  72,  73,  12,   8,
        74,  24,  30,   3,  50,  11,  75,  76,  30,  77,  78,  51,  22,
        14,  79,  80,  81,  82,  20,   3,  31,  37,  83,   2,  28,   6,
        84,  85,  86,  87,  38,   5,  88,  22,  39,   9,  52,  53,  14,
        54,  40,  37,  89,  11,  90,   4,  91,  25,   2,  92,  93,  18,
        94,   6,  95,  11,  12,  96,  26,  97,   6,   4,  98,  99, 100,
       101,  55,  27,  41,  12,   4, 102, 103,   9])

In [30]:
y_data[0]

array([159,  16,   9, 160, 161, 162,  20,  21,  69,  49,   5,  22,  28,
        36,  70,   2,  23,  10,  71,  29,   4,  72,  73,  12,   8,  74,
        24,  30,   3,  50,  11,  75,  76,  30,  77,  78,  51,  22,  14,
        79,  80,  81,  82,  20,   3,  31,  37,  83,   2,  28,   6,  84,
        85,  86,  87,  38,   5,  88,  22,  39,   9,  52,  53,  14,  54,
        40,  37,  89,  11,  90,   4,  91,  25,   2,  92,  93,  18,  94,
         6,  95,  11,  12,  96,  26,  97,   6,   4,  98,  99, 100, 101,
        55,  27,  41,  12,   4, 102, 103,   9, 104])

In [39]:
class PositionalEncoding(layers.Layer):
    def __init__(self, max_len, d_model):
        super().__init__()
        pos = np.arange(max_len)[:, np.newaxis]
        i = np.arange(d_model)[np.newaxis, :]
        angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(d_model))
        angle_rads = pos * angle_rates
        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
        self.pos_encoding = tf.cast(angle_rads[np.newaxis, ...], dtype=tf.float32)

    def call(self, x):
        return x + self.pos_encoding[:, :tf.shape(x)[1], :]

In [48]:
def transformer_block(embed_dim, num_heads, ff_dim, dropout=0.1):
    inputs = layers.Input(shape=(None, embed_dim))
    attn_output = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)(inputs, inputs)
    attn_output = layers.Dropout(dropout)(attn_output)
    out1 = layers.LayerNormalization(epsilon=1e-6)(inputs + attn_output)

    ffn = tf.keras.Sequential([
        layers.Dense(ff_dim, activation='relu'),
        layers.Dense(embed_dim),
    ])
    ffn_output = ffn(out1)
    ffn_output = layers.Dropout(dropout)(ffn_output)
    out2 = layers.LayerNormalization(epsilon=1e-6)(out1 + ffn_output)
    return tf.keras.Model(inputs=inputs, outputs=out2)

In [54]:
vocab_size = 5000
max_seq_len = 100
embed_dim = 256
num_heads = 8
ff_dim = 1024
num_layers = 96
batch_size = 32
epoch  = 10

def build_gpt_model():
    inputs = layers.Input(shape=(max_seq_len,))
    x = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)(inputs)
    x = PositionalEncoding(max_seq_len, embed_dim)(x)

    for _ in range(num_layers):
        x = transformer_block(embed_dim, num_heads, ff_dim)(x)

    outputs = layers.Dense(vocab_size, activation='softmax')(x)
    return tf.keras.Model(inputs, outputs)

In [55]:
model = build_gpt_model()
model.compile(optimizer='adam' , loss = 'sparse_categorical_crossentropy' , metrics=['accuracy'])

In [51]:
model.fit(x_data,y_data , batch_size=batch_size , epochs=epoch ,validation_split=.1)

Epoch 1/10
22/22 [==============================] - 30s 1s/step - loss: 6.2080 - accuracy: 0.0272 - val_loss: 7.4618 - val_accuracy: 0.0437
Epoch 2/10
22/22 [==============================] - 27s 1s/step - loss: 5.3467 - accuracy: 0.0326 - val_loss: 7.4266 - val_accuracy: 0.0437
Epoch 3/10
22/22 [==============================] - 29s 1s/step - loss: 5.3287 - accuracy: 0.0315 - val_loss: 7.6423 - val_accuracy: 0.0437
Epoch 4/10
22/22 [==============================] - 31s 1s/step - loss: 5.3311 - accuracy: 0.0324 - val_loss: 7.4861 - val_accuracy: 0.0468
Epoch 5/10
22/22 [==============================] - 30s 1s/step - loss: 5.3311 - accuracy: 0.0319 - val_loss: 7.4382 - val_accuracy: 0.0468
Epoch 6/10
22/22 [==============================] - 30s 1s/step - loss: 5.3262 - accuracy: 0.0327 - val_loss: 7.5357 - val_accuracy: 0.0468
Epoch 7/10
22/22 [==============================] - 30s 1s/step - loss: 5.3310 - accuracy: 0.0331 - val_loss: 7.5706 - val_accuracy: 0.0468
Epoch 8/10
22/22 [==============================] - 31s 1s/step - loss: 5.3278 - accuracy: 0.0323 - val_loss: 7.4397 - val_accuracy: 0.0437
Epoch 9/10
22/22 [==============================] - 32s 1s/step - loss: 5.3330 - accuracy: 0.0327 - val_loss: 7.4822 - val_accuracy: 0.0468
Epoch 10/10
22/22 [==============================] - 31s 1s/step - loss: 5.3389 - accuracy: 0.0322 - val_loss: 7.5497 - val_accuracy: 0.0437

In [52]:
model.save('gpt_test_genai_class.h5')

c:\Users\scl\OneDrive\Documents\projects\phitest\.conda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [56]:
model.summary()

Model: "model_101"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_14 (InputLayer)       [(None, 100)]             0

 embedding_5 (Embedding)     (None, 100, 256)          1280000

 positional_encoding_5 (Pos  (None, 100, 256)          0
 itionalEncoding)

 model_5 (Functional)        (None, None, 256)         2630144

 model_6 (Functional)        (None, None, 256)         2630144

 model_7 (Functional)        (None, None, 256)         2630144

 model_8 (Functional)        (None, None, 256)         2630144

 model_9 (Functional)        (None, None, 256)         2630144

 model_10 (Functional)       (None, None, 256)         2630144

 model_11 (Functional)       (None, None, 256)         2630144

 model_12 (Functional)       (None, None, 256)         2630144

 model_13 (Functional)       (None, None, 256)         2630144

 model_14 (Functional)       (None, None, 256)         2630144

 model_15 (Functional)       (None, None, 256)         2630144

 model_16 (Functional)       (None, None, 256)         2630144

 model_17 (Functional)       (None, None, 256)         2630144

 model_18 (Functional)       (None, None, 256)         2630144

 model_19 (Functional)       (None, None, 256)         2630144

 model_20 (Functional)       (None, None, 256)         2630144

 model_21 (Functional)       (None, None, 256)         2630144

 model_22 (Functional)       (None, None, 256)         2630144

 model_23 (Functional)       (None, None, 256)         2630144

 model_24 (Functional)       (None, None, 256)         2630144

 model_25 (Functional)       (None, None, 256)         2630144

 model_26 (Functional)       (None, None, 256)         2630144

 model_27 (Functional)       (None, None, 256)         2630144

 model_28 (Functional)       (None, None, 256)         2630144

 model_29 (Functional)       (None, None, 256)         2630144

 model_30 (Functional)       (None, None, 256)         2630144

 model_31 (Functional)       (None, None, 256)         2630144

 model_32 (Functional)       (None, None, 256)         2630144

 model_33 (Functional)       (None, None, 256)         2630144

 model_34 (Functional)       (None, None, 256)         2630144

 model_35 (Functional)       (None, None, 256)         2630144

 model_36 (Functional)       (None, None, 256)         2630144

 model_37 (Functional)       (None, None, 256)         2630144

 model_38 (Functional)       (None, None, 256)         2630144

 model_39 (Functional)       (None, None, 256)         2630144

 model_40 (Functional)       (None, None, 256)         2630144

 model_41 (Functional)       (None, None, 256)         2630144

 model_42 (Functional)       (None, None, 256)         2630144

 model_43 (Functional)       (None, None, 256)         2630144

 model_44 (Functional)       (None, None, 256)         2630144

 model_45 (Functional)       (None, None, 256)         2630144

 model_46 (Functional)       (None, None, 256)         2630144

 model_47 (Functional)       (None, None, 256)         2630144

 model_48 (Functional)       (None, None, 256)         2630144

 model_49 (Functional)       (None, None, 256)         2630144

 model_50 (Functional)       (None, None, 256)         2630144

 model_51 (Functional)       (None, None, 256)         2630144

 model_52 (Functional)       (None, None, 256)         2630144

 model_53 (Functional)       (None, None, 256)         2630144

 model_54 (Functional)       (None, None, 256)         2630144

 model_55 (Functional)       (None, None, 256)         2630144

 model_56 (Functional)       (None, None, 256)         2630144

 model_57 (Functional)       (None, None, 256)         2630144

 model_58 (Functional)       (None, None, 256)         2630144

 model_59 (Functional)       (None, None, 256)         2630144

 model_60 (Functional)       (None, None, 256)         2630144

 model_61 (Functional)       (None, None, 256)         2630144

 model_62 (Functional)       (None, None, 256)         2630144

 model_63 (Functional)       (None, None, 256)         2630144

 model_64 (Functional)       (None, None, 256)         2630144

 model_65 (Functional)       (None, None, 256)         2630144

 model_66 (Functional)       (None, None, 256)         2630144

 model_67 (Functional)       (None, None, 256)         2630144

 model_68 (Functional)       (None, None, 256)         2630144

 model_69 (Functional)       (None, None, 256)         2630144

 model_70 (Functional)       (None, None, 256)         2630144

 model_71 (Functional)       (None, None, 256)         2630144

 model_72 (Functional)       (None, None, 256)         2630144

 model_73 (Functional)       (None, None, 256)         2630144

 model_74 (Functional)       (None, None, 256)         2630144

 model_75 (Functional)       (None, None, 256)         2630144

 model_76 (Functional)       (None, None, 256)         2630144

 model_77 (Functional)       (None, None, 256)         2630144

 model_78 (Functional)       (None, None, 256)         2630144

 model_79 (Functional)       (None, None, 256)         2630144

 model_80 (Functional)       (None, None, 256)         2630144

 model_81 (Functional)       (None, None, 256)         2630144

 model_82 (Functional)       (None, None, 256)         2630144

 model_83 (Functional)       (None, None, 256)         2630144

 model_84 (Functional)       (None, None, 256)         2630144

 model_85 (Functional)       (None, None, 256)         2630144

 model_86 (Functional)       (None, None, 256)         2630144

 model_87 (Functional)       (None, None, 256)         2630144

 model_88 (Functional)       (None, None, 256)         2630144

 model_89 (Functional)       (None, None, 256)         2630144

 model_90 (Functional)       (None, None, 256)         2630144

 model_91 (Functional)       (None, None, 256)         2630144

 model_92 (Functional)       (None, None, 256)         2630144

 model_93 (Functional)       (None, None, 256)         2630144

 model_94 (Functional)       (None, None, 256)         2630144

 model_95 (Functional)       (None, None, 256)         2630144

 model_96 (Functional)       (None, None, 256)         2630144

 model_97 (Functional)       (None, None, 256)         2630144

 model_98 (Functional)       (None, None, 256)         2630144

 model_99 (Functional)       (None, None, 256)         2630144

 model_100 (Functional)      (None, None, 256)         2630144

 dense_205 (Dense)           (None, 100, 5000)         1285000

=================================================================
Total params: 255058824 (972.97 MB)
Trainable params: 255058824 (972.97 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________